name: blur_glass
description: A simple blur glass widget easy to use in Flutter.
version: 1.0.0+1
homepage: https://github.com/shAdow-XJY/blur_glass

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  blur_glass:
    path: ../
flutter:
  uses-material-design: true
  assets:
    - assets/
